const legendaryMascot = [
  {
    Pokemon: "Ho Oh",
    Game: "PokemonGold",
    Generations: 2,
    Type: "Fire, Flying",
    Region: "Johto",
    Year: 1999,
    Platform: "GameBoyColor",
  },
  {
    Pokemon: "Lugia",
    Game: "PokemonSilver",
    Generations: 2,
    Type: "Psychic, Flying",
    Region: "Johto",
    Year: 1999,
    Platform: "GameBoyColor",
  },
  {
    Pokemon: "Suicune",
    Game: "PokemonCrystal",
    Generations: 2,
    Type: "Water",
    Region: "Johto",
    Year: 2000,
    Platform: "GameBoyColor",
  },
  {
    Pokemon: "Groudon",
    Game: "PokemonRuby",
    Generations: 3,
    Type: "Ground",
    Region: "Hoenn",
    Year: 2002,
    Platform: "GameBoyAdvance",
  },
  {
    Pokemon: "Kyogre",
    Game: "PokemonSapphire",
    Generations: 3,
    Type: "Water",
    Region: "Hoenn",
    Year: 2002,
    Platform: "GameBoyAdvance",
  },
  {
    Pokemon: "Rayquaza",
    Game: "PokemonEmerald",
    Generations: 3,
    Type: "Dragon, Flying",
    Region: "Hoenn",
    Year: 2004,
    Platform: "GameBoyAdvance",
  },
]