const legendaryMascot = [
  {
    Pokemon: "Ho Oh",
    Game: "PokemonGold",
    Generations: 2,
    Type: "Fire, Flying",
    Region: "Johto",
    Year: 1999,
    Platform: "GameBoyColor",
  },
  {
    Pokemon: "Lugia",
    Game: "PokemonSilver",
    Generations: 2,
    Type: "Psychic, Flying",
    Region: "Johto",
    Year: 1999,
    Platform: "GameBoyColor",
  },
  {
    Pokemon: "Suicune",
    Game: "PokemonCrystal",
    Generations: 2,
    Type: "Water",
    Region: "Johto",
    Year: 2000,
    Platform: "GameBoyColor",
  },
  {
    Pokemon: "Groudon",
    Game: "PokemonRuby",
    Generations: 3,
    Type: "Ground",
    Region: "Hoenn",
    Year: 2002,
    Platform: "GameBoyAdvance",
  },
  {
    Pokemon: "Kyogre",
    Game: "PokemonSapphire",
    Generations: 3,
    Type: "Water",
    Region: "Hoenn",
    Year: 2002,
    Platform: "GameBoyAdvance",
  },
  {
    Pokemon: "Rayquaza",
    Game: "PokemonEmerald",
    Generations: 3,
    Type: "Dragon, Flying",
    Region: "Hoenn",
    Year: 2004,
    Platform: "GameBoyAdvance",
  },
  {
    Pokemon: "Dialga",
    Game: "PokemonDiamond",
    Generations: 4,
    Type: "Steel, Dragon",
    Region: "Sinnoh",
    Year: 2006,
    Platform: "NintendoDS",
  },
  {
    Pokemon: "Palkia",
    Game: "PokemonPearl",
    Generations: 4,
    Type: "Water, Dragon",
    Region: "Sinnoh",
    Year: 2006,
    Platform: "NintendoDS",
  },
  {
    Pokemon: "Giratina",
    Game: "PokemonPlatinum",
    Generations: 4,
    Type: "Ghost, Dragon",
    Region: "Sinnoh",
    Year: 2008,
    Platform: "NintendoDS",
  },
  {
    Pokemon: "Reshiram",
    Game: "PokemonBlack",
    Generations: 5,
    Type: "Dragon, Fire",
    Region: "Unova",
    Year: 2010,
    Platform: "NintendoDS",
  },
  {
    Pokemon: "Zekrom",
    Game: "PokemonWhite",
    Generations: 5,
    Type: "Dragon, Electric",
    Region: "Unova",
    Year: 2010,
    Platform: "NintendoDS",
  },
  {
    Pokemon: "Black Kyurem",
    Game: "PokemonBlack2",
    Generations: 5,
    Type: "Dragon, Ice",
    Region: "Unova",
    Year: 2012,
    Platform: "NintendoDS",
  },
  {
    Pokemon: "White Kyurem",
    Game: "PokemonWhite2",
    Generations: 5,
    Type: "Dragon, Ice",
    Region: "Unova",
    Year: 2012,
    Platform: "NintendoDS",
  },
  {
    Pokemon: "Xerneas",
    Game: "PokemonX",
    Generations: 6,
    Type: "Fairy",
    Region: "Kalos",
    Year: 2013,
    Platform: "Nintendo3DS",
  },
  {
    Pokemon: "Yveltal",
    Game: "PokemonY",
    Generations: 6,
    Type: "Dark, Flying",
    Region: "Kalos",
    Year: 2013,
    Platform: "Nintendo3DS",
  },
  {
    Pokemon: "Solgaleo",
    Game: "PokemonSun",
    Generations: 7,
    Type: "Psychic, Steel",
    Region: "Alola",
    Year: 2016,
    Platform: "Nintendo3DS",
  },
  {
    Pokemon: "Lunala",
    Game: "PokemonMoon",
    Generations: 7,
    Type: "Psychic, Ghost",
    Region: "Alola",
    Year: 2016,
    Platform: "Nintendo3DS",
  },
  {
    Pokemon: "Dusk Mane Necorzma",
    Game: "PokemonUltraSun",
    Generations: 7,
    Type: "Psychic, Steel",
    Region: "Alola",
    Year: 2017,
    Platform: "Nintendo3DS",
  },
  {
    Pokemon: "Dawn Wings Necrozma",
    Game: "PokemonUltraMoon",
    Generations: 7,
    Type: "Psychic, Ghost",
    Region: "Alola",
    Year: 2017,
    Platform: "Nintendo3DS",
  },
  {
    Pokemon: "Zacian",
    Game: "PokemonSword",
    Generations: 8,
    Type: "Fairy, Steel",
    Region: "Galar",
    Year: 2019,
    Platform: "NintendoSwitch",
  },
  {
    Pokemon: "Zamazenta",
    Game: "PokemonShield",
    Generations: 8,
    Type: "Fighting, Steel",
    Region: "Galar",
    Year: 2019,
    Platform: "NintendoSwitch",
  },
  {
    Pokemon: "Koraidon",
    Game: "PokemonScarlet",
    Generations: 9,
    Type: "Unknown",
    Region: "Paldea",
    Year: 2022,
    Platform: "NintendoSwitch",
  },
  {
    Pokemon: "Miraidon",
    Game: "PokemonViolet",
    Generations: 9,
    Type: "Unknown",
    Region: "Paldea",
    Year: 2022,
    Platform: "NintendoSwitch",
  }
]